version: "3.6"
services:
  pdf2svg:
    container_name: handywedge-pdf2svg
    image: handywedge/pdf2svg:master
    environment:
      LC_ALL: ja_JP.UTF-8
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ./docker/pdf2svg:/converters/pdf2svg
    ports:
      - "8081:8080"
    restart: always
